### ISSUE TITLE
File Name Mismatch

### ISSUE THREAD

**Issue by salinaf5** [mwiget/f5-xc-k8s-sites#1]
in [README.md](https://github.com/mwiget/f5-xc-k8s-sites/blob/66b7f8f2a7dd2d4da8159d7e385e6d51610e03bc/README.md?plain=1#L13), is [terragrunt.hcl.example](https://github.com/mwiget/f5-xc-k8s-sites/blob/main/terragrunt.hcl.example) the file referring to?

**Comment by mwiget** [comment]
yes. Forgot to mention to copy the terragrunt.hcl.example to terragrunt.hcl and eit accordingly.
